name: netflix
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/symbol.png"
  ios: true
  background_color: "#000000"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: "assets/images/symbol.png"
  android_12:
    image: "assets/images/symbol.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/